import Head from 'next/head'
import Home from '../pages/home/index.jsx'

function Index() {
  return (
    <>
    <Head>
        <title>Random Cine</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home />
      </>
  )
}

export default Index;
